export const Certifications = [
  {
    id: 1,
    name: "MERN Stack | A2it Online Pvt. Ltd.",
    tags: ["ReactJS", "MongoDB", "NodeJS"],
    date: "June 03, 2023",
    imgSrc: "https://i.imgur.com/zLuO6Id.png",
    link: "https://drive.google.com/file/d/1IsY2qIs1rBV7XLZFS4VfciKgAWqxncDw/view?usp=sharing/",
  },
  {
    id: 2,
    name: "ReactJs | ThinkNext Techonologies Pvt. Ltd.",
    tags: ["ReactJS"],
    date: "July 31, 2021",
    imgSrc: "https://i.imgur.com/OXlxFwF.png",
    link: "https://certificates.thinknexttraining.com/en/verify/85494246192917/",
  },
  {
    id: 3,
    name: "SQL (Basic) | HackerRank",
    tags: ["SQL"],
    date: "Sep 29, 2021",
    imgSrc: "https://i.imgur.com/i2fxuPt.jpg",
    link: "https://www.hackerrank.com/certificates/aa092616e2d1/",
  },
  {
    id: 4,
    name: "React (Basic) | HackerRank",
    tags: ["ReactJS"],
    date: "Sep 28, 2021",
    imgSrc: "https://i.imgur.com/6KrZAGd.jpg",
    link: "https://www.hackerrank.com/certificates/18fb8a9f4368/",
  },
  // {
  //   id: 5,
  //   name: "Introduction to Python | Coding Ninjas",
  //   tags: ["Python"],
  //   date: "Sep 27, 2020",
  //   imgSrc: "https://i.imgur.com/9hRqqgw.png",
  //   link: "https://ninjasfiles.s3.amazonaws.com/certificate10579455ae927e27c9741d63d3f039c4a7f566e.pdf",
  // },
  {
    id: 6,
    name: "C (Advanced) | HackerRank",
    tags: ["C"],
    date: "Sep 15, 2020",
    imgSrc: "https://i.imgur.com/p0s9ZXC.jpg",
    link: "https://www.hackerrank.com/certificates/53f0b0236fe8/",
  },
  // {
  //   id: 7,
  //   name: "C++ For C Programmers | Coursera",
  //   tags: ["C++"],
  //   date:"May 28, 2020",
  //   imgSrc:
  //     "https://i.imgur.com/r1iiCyc.png",
  //   link: "https://www.coursera.org/account/accomplishments/certificate/94PDADY56XCY/",
  // },
  // {
  //   id: 8,
  //   name: "Introduction to CSS3 | Coursera",
  //   tags: ["CSS"],
  //   date:"May 24, 2020",
  //   imgSrc: "https://i.imgur.com/s4qkIn7.png",
  //   link: "https://www.coursera.org/account/accomplishments/certificate/NUEWY98LUPZT/",
  // },
  // {
  //   id: 9,
  //   name: "C for Everyone: Programming Fundamentals | Coursera",
  //   tags: ["C"],
  //   date:"May 11, 2020",
  //   imgSrc:
  //     "https://i.imgur.com/NFPpu4O.png",
  //   link: "https://www.coursera.org/account/accomplishments/certificate/UZ2X95M7KNDL/",
  // },
  // {
  //   id: 10,
  //   name: "Introduction to HTML5 | Coursera",
  //   tags: ["HTML"],
  //   date:"May 08, 2020",
  //   imgSrc:
  //     "https://i.imgur.com/lgwFfhK.png",
  //   link: "https://www.coursera.org/account/accomplishments/certificate/NUEWY98LUPZT/",
  // },
];
